import os
import markdown
import re

TEMPLATE = """<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
    <style>
      :root {{
        --bg-color: #0d1117;
        --text-color: #c9d1d9;
        --accent-color: #238636;
        --card-bg: #161b22;
        --border-color: #30363d;
        --code-font: "Consolas", "Monaco", monospace;
      }}
      body {{
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
        background-color: var(--bg-color);
        color: var(--text-color);
        margin: 0;
        padding: 20px;
        line-height: 1.6;
      }}
      .container {{
        max-width: 900px;
        margin: 0 auto;
      }}
      h1 {{ font-size: 2rem; border-bottom: 1px solid var(--border-color); padding-bottom: 10px; margin-bottom: 20px; }}
      h2 {{ font-size: 1.5rem; margin-top: 30px; margin-bottom: 15px; color: #58a6ff; }}
      h3 {{ font-size: 1.2rem; margin-top: 25px; margin-bottom: 10px; color: #79c0ff; }}
      a {{ color: #58a6ff; text-decoration: none; }}
      a:hover {{ text-decoration: underline; }}
      ul, ol {{ padding-left: 20px; }}
      li {{ margin-bottom: 5px; }}
      pre {{
        background-color: var(--card-bg);
        border: 1px solid var(--border-color);
        padding: 15px;
        border-radius: 6px;
        overflow-x: auto;
      }}
      code {{
        font-family: var(--code-font);
        background-color: rgba(110, 118, 129, 0.4);
        padding: 0.2em 0.4em;
        border-radius: 3px;
        font-size: 85%;
      }}
      pre code {{
        background-color: transparent;
        padding: 0;
        font-size: 100%;
      }}
      blockquote {{
        border-left: 4px solid var(--border-color);
        padding-left: 15px;
        color: #8b949e;
        margin: 0;
      }}
      table {{
        border-collapse: collapse;
        width: 100%;
        margin: 20px 0;
      }}
      th, td {{
        border: 1px solid var(--border-color);
        padding: 10px;
        text-align: left;
      }}
      th {{ background-color: var(--card-bg); }}
    </style>
  </head>
  <body>
    <div class="container">
      <p><a href="../../index.html">← Back to Hub</a></p>
      {content}
      <footer style="margin-top: 50px; text-align: center; font-size: 0.8rem; color: #8b949e;">
        <p>Generated by Gemini CLI Agent</p>
      </footer>
    </div>
  </body>
</html>
"""

def convert_single_file(md_path, html_path=None):
    """
    Converts a single markdown file to HTML using the dark theme template.
    If html_path is not provided, it defaults to the same path with .html extension.
    Returns the path of the generated HTML file.
    """
    if not os.path.exists(md_path):
        raise FileNotFoundError(f"File not found: {md_path}")

    if html_path is None:
        html_path = os.path.splitext(md_path)[0] + ".html"

    with open(md_path, "r", encoding="utf-8") as f:
        text = f.read()

    # Simple YAML frontmatter stripping
    if text.strip().startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            text = parts[2]

    html_content = markdown.markdown(text, extensions=['fenced_code', 'tables'])

    # Extract title
    title_match = re.search(r'<h1>(.*?)</h1>', html_content)
    title = title_match.group(1) if title_match else os.path.basename(md_path)

    final_html = TEMPLATE.format(title=title, content=html_content)

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(final_html)
    
    return html_path

def convert_md_files():
    # Walk through playbook directory
    for root, dirs, files in os.walk("playbook"):
        if "99_appendix" in root:
            continue 
        
        for file in files:
            if file.endswith(".md") and file != "README.md":
                md_path = os.path.join(root, file)
                print(f"Converting {md_path}...")
                convert_single_file(md_path)

def update_index_links():
    print("Updating index.html links...")
    with open("index.html", "r", encoding="utf-8") as f:
        content = f.read()
    
    def replace_link(match):
        path = match.group(1)
        if path.startswith("playbook") and path.endswith(".md"):
            return f'href="{path[:-3]}.html"'
        return match.group(0)

    new_content = re.sub(r'href="(playbook/[^"]+\.md)"', replace_link, content)
    
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(new_content)

def fix_browser_works():
    path = "playbook/99_appendix/how_browser_works.html"
    print(f"Fixing {path}...")
    
    if not os.path.exists(path):
        print(f"Error: {path} not found")
        return

    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
        
    # Extract inner content from body. 
    # The file has <div class="container">...</div>
    match = re.search(r'<div class="container">(.*?)</div>', content, re.DOTALL)
    if match:
        inner_content = match.group(1)
        # Use a generic title or extract H1
        h1_match = re.search(r'<h1>(.*?)</h1>', inner_content)
        title = h1_match.group(1) if h1_match else "Browser Internals"
        
        final_html = TEMPLATE.format(title=title, content=inner_content)
        
        with open(path, "w", encoding="utf-8") as f:
            f.write(final_html)
    else:
        # Fallback if no container div found
        body_match = re.search(r'<body>(.*?)</body>', content, re.DOTALL)
        if body_match:
             final_html = TEMPLATE.format(title="Browser Internals", content=body_match.group(1))
             with open(path, "w", encoding="utf-8") as f:
                f.write(final_html)
        else:
            print("Could not parse how_browser_works.html")

if __name__ == "__main__":
    convert_md_files()
    update_index_links()
    fix_browser_works()
